services:
  bot:
    image: ghcr.io/dingledangledoff/trustworthy-protogen-new:latest
    container_name: trustworthy-protogen-bot
    restart: unless-stopped
    environment:
      - token=${token}
      - blockedUsers=${blockedUsers}
      - wolframAPI=${wolframAPI}
      - geminiAPI=${geminiAPI}
      - clientId=${clientId}
      - guildId=${guildId}
      - dataDir=/data
    volumes:
      - ./data:/data
